/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppTextRouteImport } from './routes/app.text'
import { Route as AppStudentGuideRouteImport } from './routes/app.student-guide'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSavedRouteImport } from './routes/app.saved'
import { Route as AppRoleplayRouteImport } from './routes/app.roleplay'
import { Route as AppImageRouteImport } from './routes/app.image'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDocumentRouteImport } from './routes/app.document'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppStudentGuideCountryRouteImport } from './routes/app.student-guide.$country'
import { Route as AppStudentGuideCountryCategoryRouteImport } from './routes/app.student-guide.$country.$category'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppTextRoute = AppTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentGuideRoute = AppStudentGuideRouteImport.update({
  id: '/student-guide',
  path: '/student-guide',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleplayRoute = AppRoleplayRouteImport.update({
  id: '/roleplay',
  path: '/roleplay',
  getParentRoute: () => AppRoute,
} as any)
const AppImageRoute = AppImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentRoute = AppDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentGuideCountryRoute = AppStudentGuideCountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => AppStudentGuideRoute,
} as any)
const AppStudentGuideCountryCategoryRoute =
  AppStudentGuideCountryCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => AppStudentGuideCountryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/community': typeof AppCommunityRoute
  '/app/document': typeof AppDocumentRoute
  '/app/history': typeof AppHistoryRoute
  '/app/image': typeof AppImageRoute
  '/app/roleplay': typeof AppRoleplayRoute
  '/app/saved': typeof AppSavedRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-guide': typeof AppStudentGuideRouteWithChildren
  '/app/text': typeof AppTextRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/': typeof AppIndexRoute
  '/app/student-guide/$country': typeof AppStudentGuideCountryRouteWithChildren
  '/app/student-guide/$country/$category': typeof AppStudentGuideCountryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/community': typeof AppCommunityRoute
  '/app/document': typeof AppDocumentRoute
  '/app/history': typeof AppHistoryRoute
  '/app/image': typeof AppImageRoute
  '/app/roleplay': typeof AppRoleplayRoute
  '/app/saved': typeof AppSavedRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-guide': typeof AppStudentGuideRouteWithChildren
  '/app/text': typeof AppTextRoute
  '/app/voice': typeof AppVoiceRoute
  '/app': typeof AppIndexRoute
  '/app/student-guide/$country': typeof AppStudentGuideCountryRouteWithChildren
  '/app/student-guide/$country/$category': typeof AppStudentGuideCountryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/community': typeof AppCommunityRoute
  '/app/document': typeof AppDocumentRoute
  '/app/history': typeof AppHistoryRoute
  '/app/image': typeof AppImageRoute
  '/app/roleplay': typeof AppRoleplayRoute
  '/app/saved': typeof AppSavedRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-guide': typeof AppStudentGuideRouteWithChildren
  '/app/text': typeof AppTextRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/': typeof AppIndexRoute
  '/app/student-guide/$country': typeof AppStudentGuideCountryRouteWithChildren
  '/app/student-guide/$country/$category': typeof AppStudentGuideCountryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/community'
    | '/app/document'
    | '/app/history'
    | '/app/image'
    | '/app/roleplay'
    | '/app/saved'
    | '/app/settings'
    | '/app/student-guide'
    | '/app/text'
    | '/app/voice'
    | '/app/'
    | '/app/student-guide/$country'
    | '/app/student-guide/$country/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/community'
    | '/app/document'
    | '/app/history'
    | '/app/image'
    | '/app/roleplay'
    | '/app/saved'
    | '/app/settings'
    | '/app/student-guide'
    | '/app/text'
    | '/app/voice'
    | '/app'
    | '/app/student-guide/$country'
    | '/app/student-guide/$country/$category'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/community'
    | '/app/document'
    | '/app/history'
    | '/app/image'
    | '/app/roleplay'
    | '/app/saved'
    | '/app/settings'
    | '/app/student-guide'
    | '/app/text'
    | '/app/voice'
    | '/app/'
    | '/app/student-guide/$country'
    | '/app/student-guide/$country/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/text': {
      id: '/app/text'
      path: '/text'
      fullPath: '/app/text'
      preLoaderRoute: typeof AppTextRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student-guide': {
      id: '/app/student-guide'
      path: '/student-guide'
      fullPath: '/app/student-guide'
      preLoaderRoute: typeof AppStudentGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saved': {
      id: '/app/saved'
      path: '/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roleplay': {
      id: '/app/roleplay'
      path: '/roleplay'
      fullPath: '/app/roleplay'
      preLoaderRoute: typeof AppRoleplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/image': {
      id: '/app/image'
      path: '/image'
      fullPath: '/app/image'
      preLoaderRoute: typeof AppImageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/document': {
      id: '/app/document'
      path: '/document'
      fullPath: '/app/document'
      preLoaderRoute: typeof AppDocumentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student-guide/$country': {
      id: '/app/student-guide/$country'
      path: '/$country'
      fullPath: '/app/student-guide/$country'
      preLoaderRoute: typeof AppStudentGuideCountryRouteImport
      parentRoute: typeof AppStudentGuideRoute
    }
    '/app/student-guide/$country/$category': {
      id: '/app/student-guide/$country/$category'
      path: '/$category'
      fullPath: '/app/student-guide/$country/$category'
      preLoaderRoute: typeof AppStudentGuideCountryCategoryRouteImport
      parentRoute: typeof AppStudentGuideCountryRoute
    }
  }
}

interface AppStudentGuideCountryRouteChildren {
  AppStudentGuideCountryCategoryRoute: typeof AppStudentGuideCountryCategoryRoute
}

const AppStudentGuideCountryRouteChildren: AppStudentGuideCountryRouteChildren =
  {
    AppStudentGuideCountryCategoryRoute: AppStudentGuideCountryCategoryRoute,
  }

const AppStudentGuideCountryRouteWithChildren =
  AppStudentGuideCountryRoute._addFileChildren(
    AppStudentGuideCountryRouteChildren,
  )

interface AppStudentGuideRouteChildren {
  AppStudentGuideCountryRoute: typeof AppStudentGuideCountryRouteWithChildren
}

const AppStudentGuideRouteChildren: AppStudentGuideRouteChildren = {
  AppStudentGuideCountryRoute: AppStudentGuideCountryRouteWithChildren,
}

const AppStudentGuideRouteWithChildren = AppStudentGuideRoute._addFileChildren(
  AppStudentGuideRouteChildren,
)

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppDocumentRoute: typeof AppDocumentRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppImageRoute: typeof AppImageRoute
  AppRoleplayRoute: typeof AppRoleplayRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentGuideRoute: typeof AppStudentGuideRouteWithChildren
  AppTextRoute: typeof AppTextRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppDocumentRoute: AppDocumentRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppImageRoute: AppImageRoute,
  AppRoleplayRoute: AppRoleplayRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentGuideRoute: AppStudentGuideRouteWithChildren,
  AppTextRoute: AppTextRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
